# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hugo-zerigo_dns}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Wilson"]
  s.date = %q{2010-02-07}
  s.description = %q{}
  s.email = %q{tom@jackhq.com}
  s.files = [
    "Rakefile",
     "lib/hugo-zerigo_dns.rb",
     "lib/hugo/cloud-zerigo_dns.rb",
     "lib/hugo/dns.rb"
  ]
  s.homepage = %q{http://github.com/twilson63/hugo-zerigo_dns}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Hugo Plug-in that gives you automated access to zerigo_dns}
  s.test_files = [
    "spec/lib/hugo/dns_spec.rb",
     "spec/lib/hugo_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hugo>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_runtime_dependency(%q<activeresource>, [">= 2.3.5"])
      s.add_runtime_dependency(%q<zerigo_dns>, [">= 1.0.0"])
    else
      s.add_dependency(%q<hugo>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<activeresource>, [">= 2.3.5"])
      s.add_dependency(%q<zerigo_dns>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<hugo>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<activeresource>, [">= 2.3.5"])
    s.add_dependency(%q<zerigo_dns>, [">= 1.0.0"])
  end
end

